NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
default       predict-app-c9bbf48d9-jt5zf        1/1     Running   0          67s
kube-system   coredns-f9fd979d6-j9xbt            1/1     Running   0          5m34s
kube-system   etcd-minikube                      1/1     Running   0          5m39s
kube-system   kube-apiserver-minikube            1/1     Running   0          5m39s
kube-system   kube-controller-manager-minikube   1/1     Running   0          5m39s
kube-system   kube-proxy-4xsxj                   1/1     Running   0          5m34s
kube-system   kube-scheduler-minikube            1/1     Running   0          5m39s
kube-system   storage-provisioner                1/1     Running   0          5m39s
Error from server (AlreadyExists): services "predict-app" already exists
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000

# After running kubectl logs ${pod-name} #

* Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 204-671-445
[2020-11-22 16:28:05,017] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2020-11-22 16:28:05,036] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2020-11-22 16:28:05,047] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2020-11-22 16:28:05,053] INFO in app: Output prediction: 
[20.35373177134412]

# After running minikube delete #

E1121 15:23:04.984488   44702 portforward.go:233] lost connection to pod
